Repository Minecraft-Eternal/MC-Eternal-1.12, pull requests merged in 2021-05, with the labels that each got.

#165 Fix erebus-waila
  Client/manifest.json
  Client/modlist.html
Labels: Bug PR

#179 Allow use of any Angel Ring variant to craft other variants
  Client/overrides/scripts/ExtraUtils.zs
Labels: Feature PR, enhancement

#182 Fix Chop Chop quest
  Client/overrides/config/ftbquests/normal/189d88b6/3c47dd85.snbt
Labels: Bug PR

#184 Consider removing normal preprocessor from AdvRocketry.zs
  Client/overrides/scripts/AdvRocketry.zs
Labels: Bug PR

#185 Add Sphere of Cognizance quest
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/20813292.snbt
Labels: Feature PR

#189 Adding the biome'o plenty biomes to the whitelist
  Client/overrides/config/laser_drill_ores/mce_custom.json
Labels: enhancement

#187 A little warning about autocraft
  Client/overrides/scripts/Tooltip.zs
Labels: enhancement

#194 updating nether spreading message
  Client/overrides/config/netherportalspread.cfg
Labels: enhancement

#195 Prevent starlight corruption
  Client/overrides/config/cyclicmagic.cfg
Labels: Bug PR, Feature PR, enhancement
