Repository Minecraft-Eternal/MC-Eternal-1.12, pull requests merged in 2021-07, with the labels that each got.

#231 Make Legendary Infinity Drill quest only accept Legendary drills
  Client/overrides/config/ftbquests/classic/chapters/3bc6db27/1f1dad8c.snbt
  Client/overrides/config/ftbquests/normal/chapters/3bc6db27/1f1dad8c.snbt
Labels: Bug PR

#227 Buff Atum Mobs and properly apply spawncap to Moon mobs
  Client/overrides/config/incontrol/potentialspawn.json
  Client/overrides/config/incontrol/spawn.json
Labels: Bug PR, Feature PR

#226 Blackmarket and Common lootbox cleanup
  Client/overrides/config/ftbquests/normal/reward_tables/8e152c32.snbt
  Client/overrides/config/ftbquests/normal/reward_tables/dad26af0.snbt
Labels: Bug PR

#222 Make Wing Durability stats equal
  Client/overrides/config/wings/items.cfg
Labels: Feature PR

#202 Remove some problematic/duplicate Shop items
  Client/overrides/config/ftbmoneyshop.nbt
Labels: Bug PR

#186 Add EBWizardry Lectern quest
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/a3b469ab.snbt
Labels: Feature PR

#172 Move Builder recipe alteration to Quarry Card
  Client/overrides/scripts/RFTools.zs
Labels: Feature PR

#238 Make naturally spawning F&A mobs more rare
  Client/overrides/config/fossil.cfg
Labels: Bug PR

#239 Remove FTBUtils Claim restrictions
  Client/overrides/config/ftbutilities.cfg
Labels: Feature PR

#243 Reduce Banshee damage to 30 from 70
  Client/overrides/config/Fishs_Undead_Rising.cfg
Labels: Feature PR

#242 Fix the induction smelter of clock and compass
  Client/overrides/scripts/ConflictFix.zs
Labels: Bug PR, enhancement

#233 Chop Chop quest was missing again
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/3c47dd85.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/3c47dd85.snbt
Labels: Bug PR

#241 Create MobGrindingUtils.zs and disable some items from the mod
  Client/overrides/scripts/MobGrindingUtils.zs
Labels: Feature PR

#167 Buff Lategame Tinkers' Materials
  Client/overrides/config/tweakersconstruct.cfg
Labels: Feature PR

#264 No use for ShadowMC and LunatriusCore
  Client/manifest.json
Labels: Feature PR

#232 fixing some errors in scripts for the new release
  Client/overrides/scripts/AdvRocketry.zs
  Client/overrides/scripts/Tooltip.zs
Labels: Bug PR

#246 Update Events
  Client/overrides/scripts/Events.zs
Labels: Feature PR

#247 Fix IE Crusher recipes in TaigaDusts.zs
  Client/overrides/scripts/TaigaDusts.zs
Labels: Bug PR

#248 Add Disabled tooltips to Pam's Gardens
  Client/overrides/scripts/Harvestcraft.zs
Labels: Bug PR

#250 Remove overly cheap Steel Blend recipes
  Client/overrides/config/unidict/UniDict.cfg
Labels: Bug PR

#251 Blacklist Rats from Erebus and DimDoors dimensions
  Client/overrides/config/rats.cfg
Labels: Bug PR

#252 Make Revolver Bullet Damage tooltip more accurate
  Client/overrides/scripts/Tooltip.zs
Labels: Bug PR

#254 Set RFTools Dimensions respawn dimension back to 0
  Client/overrides/config/rftools/dimensions.cfg
Labels: Bug PR

#255 Extend AE2 Meteor tooltip to Meteorite Compass and add Minesweeper warning
  Client/overrides/scripts/Tooltip.zs
Labels: Feature PR

#256 Disable Blood Magic Flight potion flask
  Client/overrides/scripts/BloodMagic.zs
Labels: Bug PR

#257 Fix Problematic TCon traits better
  Client/overrides/config/tweakersconstruct.cfg
Labels: Bug PR, Feature PR

#258 Make Power Fist recipe work with any Charge state of Drill
  Client/overrides/scripts/Powersuits.zs
Labels: Feature PR

#260 Make RFTools Shield actually usable
  Client/overrides/config/rftools/rftools.cfg
Labels: Bug PR

#261 Allow Dimension Builder to accept entire capacity of RF/t
  Client/overrides/config/rftools/dimensions.cfg
Labels: Bug PR, Feature PR

#262 Add Juniperberry seed to Cooking for Blockheads market
  Client/overrides/config/FarmingForBlockheads/Market.json
Labels: Bug PR

#263 Make Primordial Planes star a Black Hole
  Client/overrides/config/advRocketry/planetDefs.xml
Labels: Feature PR

#272 Block access to Space-gated Dimensions via their Portals
  Client/overrides/scripts/NoSpacePortals.zs
Labels: Bug PR, Feature PR

#249 Alter Railgun and Revolver recipes to reflect buff
  Client/overrides/scripts/Immersive.zs
Labels: Feature PR

#259 Add Impulse Cannon augment damage buff tooltip
  Client/overrides/scripts/Tooltip.zs
Labels: Feature PR

#268 Buff Primal Cutter
  Client/overrides/config/thaumicaugmentation.cfg
Labels: Feature PR

#269 Double Impulse Cannon Railgun range
  Client/overrides/config/thaumicaugmentation.cfg
Labels: Feature PR

#270 Add quest "News on Nuclear Science"
  Client/overrides/config/ftbquests/classic/chapters/3f8f0656/a58c7c02.snbt
  Client/overrides/config/ftbquests/normal/chapters/3f8f0656/a58c7c02.snbt
Labels: Feature PR

#271 Replace Endertweaker script lines with EnderIO XML recipes and update EIO
  Client/manifest.json
  Client/overrides/config/enderio/recipes/user/SAG_taiga_dust.xml
  Client/overrides/config/enderio/recipes/user/mce_fixes.xml
  Client/overrides/scripts/EnderIO.zs
  Client/overrides/scripts/TaigaDusts.zs
Labels: Feature PR

#273 everlasting food goes rotting
  Client/overrides/config/thebetweenlands/config.cfg
Labels: Feature PR

#274 Delete Adam's worldSettings from JEI
  Client/overrides/config/jei/worldSettings.cfg
Labels: Feature PR

#275 prevent funny crash with thaumcraft
  Client/overrides/config/thaumcraft_world.cfg
Labels: Bug PR, Feature PR, help wanted

#278 Update industrialforegoing.cfg
  Client/overrides/config/industrialforegoing.cfg
Labels: enhancement

#281 remove removed enchantments
  Client/overrides/config/astralsorcery/amulet_enchantments.cfg
Labels: Bug PR

#284 Nerf Netherite spawns in 04_Custom_Fix.json
  Client/overrides/config/cofh/world/04_Custom_Fix.json
Labels: Feature PR

#285 Reduce Builder RF/block placement cost
  Client/overrides/config/rftools/rftools.cfg
Labels: Feature PR

#286 Reenable TechReborn Bauxite but make it rarer
  Client/overrides/config/teamreborn/techreborn/ores.json
Labels: Feature PR

#287 Nature's Aura questline
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/009f8f45.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/13287cac.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/185e679f.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/28c0eb2b.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/4274463d.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/484f7836.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/4a1cbb3d.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/6bdef9f0.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/9303f392.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/a074c6bd.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/ab5b0787.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/b12539ba.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/c01af10c.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/c1f80434.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/c24aee0f.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/cf40c7b4.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/e5318b93.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/f94b896a.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/009f8f45.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/13287cac.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/185e679f.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/28c0eb2b.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/4274463d.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/484f7836.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/4a1cbb3d.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/6bdef9f0.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/9303f392.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/a074c6bd.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/ab5b0787.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/b12539ba.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/c01af10c.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/c1f80434.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/c24aee0f.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/cf40c7b4.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/e5318b93.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/f94b896a.snbt
Labels: Feature PR

#289 Update Treechop further
  Client/manifest.json
Labels: Bug PR, Feature PR

#279 Last Bugfixes for next release
  Client/overrides/config/enderio/recipes/user/mce_fixes.xml
  Client/overrides/config/incontrol/spawn.json
  Client/overrides/scripts/ConflictFix.zs
  Client/overrides/scripts/MobGrindingUtils.zs
Labels: Feature PR

#291 Update boron_plant.json
  Client/overrides/config/agricraft/json/defaults/mod_mysticalagriculture/plants/boron_plant.json
Labels: Bug PR
