Repository Minecraft-Eternal/MC-Eternal-1.12, pull requests merged in 2021-09, with the labels that each got.

#325 make Legendary Infinity Drill quest optional
  Client/overrides/config/ftbquests/classic/chapters/3bc6db27/1f1dad8c.snbt
  Client/overrides/config/ftbquests/normal/chapters/3bc6db27/1f1dad8c.snbt
Labels: Feature PR

#326 Remove Slaughtering Trait
  Client/overrides/config/tweakersconstruct.cfg
Labels: Bug PR

#327 Add disabled tooltip to Deep Dark portal
  Client/overrides/scripts/Tooltip.zs
Labels: Bug PR

#328 Nerf Holy Cheese
  Client/overrides/config/ftbquests/classic/chapters/2c343c21/843f9376.snbt
  Client/overrides/config/ftbquests/normal/chapters/2c343c21/843f9376.snbt
Labels: Feature PR

#329 Blacklist lots of Item holders in improvedbackpacks.cfg + disable Ender backpack durability
  Client/overrides/config/improvedbackpacks.cfg
Labels: Feature PR

#333 Update Events.zs
  Client/overrides/scripts/Events.zs
Labels: Bug PR

#334 Disable use of Mekanism Steel Casing for IF Machines
  Client/overrides/config/industrialforegoing.cfg
Labels: Feature PR

#335 Fix Hunter Axe quests
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/6931cfe5.snbt
  Client/overrides/config/ftbquests/classic/chapters/bec752d7/aa9176e5.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/6931cfe5.snbt
  Client/overrides/config/ftbquests/normal/chapters/bec752d7/aa9176e5.snbt
Labels: Bug PR

#337 Update midnight.cfg
  Client/overrides/config/midnight.cfg
Labels: Bug PR

#341 Make Erebus have a Bedrock bottom
  Client/overrides/config/wgblockreplacer.cfg
Labels: Feature PR

#348 Make Wither quest in Intro spoopier C:<
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/67039193.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/67039193.snbt
Labels: documentation, Feature PR

#345 Description in the Drill quest
  Client/overrides/config/ftbquests/classic/chapters/3bc6db27/1f1dad8c.snbt
  Client/overrides/config/ftbquests/normal/chapters/3bc6db27/1f1dad8c.snbt
Labels: documentation, Feature PR

#349 Disable Juggernaut pet
  Client/overrides/config/inventorypets/inventorypets.cfg
Labels: Feature PR

#350 Make Erebus and Aurorian not overlap in Warp Controller
  Client/overrides/config/advRocketry/planetDefs.xml
Labels: Feature PR

#351 Add recipe for Erebus' Advanced Homing Beecon
  Client/overrides/scripts/MiscCrafting.zs
Labels: Bug PR

#353 Reduce Artifacts Chest and Mimic rates
  Client/overrides/config/Artifacts.cfg
Labels: Feature PR

#354 Remove NBT tag from Shop Portal Gun
  Client/overrides/config/ftbmoneyshop.nbt
Labels: Feature PR

#356 Matrix Enchanting + Dungeonsmod Traveller quests
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/92ca1bd3.snbt
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/9e3a30c7.snbt
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/9f78a78f.snbt
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/b1b8d431.snbt
  Client/overrides/config/ftbquests/classic/chapters/189d88b6/bd0b2e95.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/92ca1bd3.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/9e3a30c7.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/9f78a78f.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/b1b8d431.snbt
  Client/overrides/config/ftbquests/normal/chapters/189d88b6/bd0b2e95.snbt
Labels: documentation, Feature PR

#357 Add Thorium Ore to Botania's Orechid
  Client/overrides/scripts/GoToTheBeneath.zs
Labels: Feature PR

#358 Fix Dimdoors quests + Refine Ratumaton quest
  Client/overrides/config/ftbquests/classic/chapters/ca973051/6da2b354.snbt
  Client/overrides/config/ftbquests/classic/chapters/ca973051/9baa413e.snbt
  Client/overrides/config/ftbquests/classic/chapters/ca973051/dbad51d0.snbt
  Client/overrides/config/ftbquests/normal/chapters/ca973051/6da2b354.snbt
  Client/overrides/config/ftbquests/normal/chapters/ca973051/9baa413e.snbt
  Client/overrides/config/ftbquests/normal/chapters/ca973051/dbad51d0.snbt
Labels: documentation, Bug PR

#360 Make Ancient Debris from Cofh worldgen rarer
  Client/overrides/config/cofh/world/04_Custom_Fix.json
Labels: Feature PR

#361 Blacklist lots of Potion effects from Pharos Beacon
  Client/overrides/config/cyclicmagic.cfg
Labels: Bug PR

#362 Make Solstice Sword illegal
  Client/overrides/scripts/Events.zs
Labels: Bug PR

#363 Add 2 funny new Challenge quests
  Client/overrides/config/ftbquests/classic/chapters/03049ff4/baad27f4.snbt
  Client/overrides/config/ftbquests/classic/chapters/03049ff4/d9d82af7.snbt
  Client/overrides/config/ftbquests/normal/chapters/03049ff4/baad27f4.snbt
  Client/overrides/config/ftbquests/normal/chapters/03049ff4/d9d82af7.snbt
Labels: Feature PR
