Repository Minecraft-Eternal/MC-Eternal-1.12, pull requests merged in 2021-08, with the labels that each got.

#311 Delete Decaster.zs, again...
  Client/overrides/scripts/Decaster.zs
Labels: Bug PR

#310 Fix #305
  Client/overrides/config/cyclicmagic.cfg
Labels: Bug PR

#294 Update thaumcraft_world.cfg
  Client/overrides/config/thaumcraft_world.cfg
Labels: Bug PR

#299 Common+Blackmarket Missing Item Cleanup
  Client/overrides/config/ftbquests/classic/reward_tables/8e152c32.snbt
  Client/overrides/config/ftbquests/classic/reward_tables/dad26af0.snbt
  Client/overrides/config/ftbquests/normal/reward_tables/dad26af0.snbt
Labels: Bug PR

#295 Update Events.zs
  Client/overrides/scripts/Events.zs
Labels: Bug PR

#300 Blacklist Dragons in End
  Client/overrides/config/ice_and_fire.cfg
Labels: Bug PR

#302 Remove Empty Station Container from ET Crates
  Client/overrides/config/ftbquests/classic/reward_tables/0cfb5327.snbt
  Client/overrides/config/ftbquests/normal/reward_tables/0cfb5327.snbt
Labels: Bug PR

#304 Blacklist a Ton of mobs from Dagger of Sacrifice
  Client/overrides/config/bloodmagic/bloodmagic.cfg
Labels: Feature PR, Bug PR

#308 Implement Netherumbrian Pipes recipe by @Handeril
  Client/overrides/scripts/ConflictFix.zs
Labels: Feature PR

#309 Tooltip adjustments + 4 New ones
  Client/overrides/scripts/Mekanism.zs
  Client/overrides/scripts/Tooltip.zs
Labels: Feature PR

#313 YAML format Issue Templates!
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/suggestion.yaml
Labels: documentation, enhancement

#301 Add Tips mod + 8 Custom tips
  Client/manifest.json
  Client/overrides/config/tips.cfg
Labels: Feature PR

#316 fix #315
  Client/overrides/config/FarmingForBlockheads/Market.json
Labels: Bug PR

#319 Add some more funny champion names
  Client/overrides/config/champions.cfg
Labels: Feature PR

#322 :bread:
  Client/overrides/config/culinaryconstruct.cfg
Labels: Feature PR

#323 delete duping Treasure2 charm effect :V
  Client/overrides/config/treasure2/loot_tables/pools/treasure/epic_charms.json
Labels: Bug PR
